data/mst/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from mst.views import *

urlpatterns = [
 
    #Example: /mst/client/list/
    url(r'^client/list/$', Client_list.as_view(), name='client_list' ),

]
handler404 = 'mysite.views.my_custom_page_not_found_view'
handler500 = 'mysite.views.my_custom_error_view'
handler403 = 'mysite.views.my_custom_permission_denied_view'
handler400 = 'mysite.views.my_custom_bad_request_view'

data/tiamo/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin

from tiamo.views import *
from django.conf import settings
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^tiamo/$', index_tiamo, name='home'),

    url(r'^mst/', include('mst.urls')),

    
###=============================================================================
###   통계 Stats
###=============================================================================
    # url: /tiamo/stats/
    # Example: tiamo/stats/
    url(r'^tiamo/stats/main/$', StatsMain.as_view(), name='stats_main'),
    


###=============================================================================
###   매입 / 구입 PURCHASE 
###=============================================================================
  
    # Example: /
    # url(r'^$', WelcomeView()),
    # Example: tiamo/purchase/
    url(r'^tiamo/purchase/main/$', PurchaseMainView.as_view(), name='purchase_main'),

    #Example: tiamo/purchase/2017/02/16/
    url(r'^tiamo/purchase/list/(?P<date>[0-9]{8})/$', PurchaseDayListView.as_view(), name='purchase_list'),

    # Example: tiamo/purchase/create/
    url(r'^tiamo/purchase/create/$', PurchaseCreateView.as_view(), name='purchase_create'),

    # Example: tiamo/purchase/10/update/
    url(r'^tiamo/purchase/(?P<pk>\d+)/update/$', PurchaseUpdateView.as_view(), name='purchase_update'),

    # Example: tiamo/purchase/10/delete/
    #url(r'^tiamo/purchase/(?P<pk>\d+)/delete/$', PurchaseDeleteView.as_view(), name='purchase_delete'),
    
    # Example: tiamo/purchase/10/
    url(r'^tiamo/purchase/(?P<pk>\d+)/$', PurchaseDetailView.as_view(), name='purchase_detail'),
    

###=============================================================================
###   판매, 막장부 , 수금장부 ORDERS 
###=============================================================================

    ##판매현황(조회일)
    #Example: tiamo/order/status/
    url(r'^tiamo/order/status/$', OrderStatus.as_view() , name='order_main'),

    ##판매현황(지정일자)
    #Example: tiamo/order/status/20170503/
    url(r'^tiamo/order/status/(?P<date>[0-9]{8})/$', OrderStatus.as_view() , name='order_main'),

    # ##판매현황(지정일자)
    # #Example: tiamo/order/status/20170503/
    # url(r'^tiamo/order/status/(?P<date>[0-9]{8})/$', OrderStatus.as_view() , name='order_main'),

    ##막장부  판매기록 신규입력
    #Example: tiamo/order/
    url(r'^tiamo/order/$', CreateOrder.as_view() , name='create_order'),
 
    ##막장부  판매기록 업데이트
    #Example: tiamo/order/update
    url(r'^tiamo/order/update/$', UpdateOrder.as_view() , name='update_order'),


    # ##막장부
    # #Example: tiamo/order/list/
    url(r'^tiamo/order/list/log/(?P<date>[0-9]{8})/$', OrderLogByDate.as_view(), name='order_log_daily') ,

    ##막장부(지정일자)
    #Example: tiamo/order/list/20170503/
    url(r'^tiamo/order/list/(?P<date>[0-9]{8})/$', OrderListByDate.as_view(), name='order_daily_list') ,
   
    # ##메뉴명 유효성 검사
    # #Example: validation/menuname/
    url(r'^validation/menuname/$', ValidateOrderMenuname.as_view() , name='menuname_check'),


    ##(판매)거래내역
    #Example: tiamo/order/history/1/
    url(r'^tiamo/order/history/(?P<client_id>[0-9])/$', OrderHistoryByClient.as_view(), name='order_history') ,
    
    url(r'^tiamo/order/history/$', OrderHistoryByClient.as_view(), name='order_history') ,

    #일일 거래내역 가져오기 
    #POST: client_id, date
    url(r'^tiamo/order/product_txt/$', TodaysOrderText.as_view(), name='todays_orders') ,
    
    
###=============================================================================
###   외상 / 수금 Payment 
###=============================================================================

    ## 누적미수금액 전체 재계산   
    url(r'^tiamo/payment/recalc/all/(?P<date>[0-9]{8})/$', PaymentRecalc.as_view(), name='payment_recalc' ),
 
    ##외상현황
    ##Example: /tiamo/payment/
    url(r'^tiamo/payment/$', PaymentState.as_view(), name='payment_state' ),
 
    ##일일막장부리스트
    #Example: tiamo/order/list/20170503/
    url(r'^tiamo/payment/(?P<date>[0-9]{8})/$', PaymentState.as_view(), name='payment_state') ,

    ##수금대상
    ##Example: /tiamo/payment/plan/
    url(r'^tiamo/payment/plan/$', PaymentPlan.as_view(), name='payment_list') ,
    
    ##일일수금대상
    ##Example: /tiamo/payment/plan/20170903/ 
    url(r'^tiamo/payment/plan/(?P<date>[0-9]{8})/$', PaymentPlan.as_view(), name='payment_list'),


    ##정산입력
    ##Example: /tiamo/payment/time/
    url(r'^tiamo/payment/time/$', Floor_list.as_view(), name='payment_time'),

    ##정산입력
    ##Example: /tiamo/payment/time/
    url(r'^tiamo/payment/time/(?P<date>[0-9]{8})/$', Floor_list.as_view(), name='payment_time'),

    ##수금처리
    ## POST
    ##Example: /tiamo/payment/payment/received/
    url(r'^tiamo/payment/received/$', Payment_received.as_view(), name="payment_received"),

 
    ##수금 연기 처리
    ## POST
    ##Example: /tiamo/payment/payment/received/
    url(r'^tiamo/payment/defer/$', Payment_defered.as_view(), name="payment_defered"),


    # ##기간 외 수금처리 대상 선택 
    # url(r'^tiamo/payment/outdate/(?P<posnum>[A-Z]{1}[0-9]{4})/$', Outdate_payment_select.as_view(), name="outdate_selected"),


    


]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

from django.conf.urls import (
    handler400, handler404, handler500
)
handler400 = 'django.views.defaults.bad_request'
handler404 = 'tiamo.views.page_not_found_page'
handler500 = 'tiamo.views.server_error_page'

data/tiamo/models.py
# -*- coding: utf-8 -*-
### CharField 에 null = True 는 권장하지 않는다.

import logging
from django.db import models
from django.db.models import   Max, Min
from django.utils import timezone
from mst.models import Product, Material, Seller, Client
from tiamo.utils import *
from datetime import date 
import datetime as datetime
from model_utils.models    import TimeStampedModel
# 모든 쿼리를 볼 수 있음 
# from django.db import connection



logger = logging.getLogger(__name__)

class PurchaseDetailManager(models.Manager):
     
    def accrued_total(self,sellers, month):
        result_data = []
        year = date.today().year
        month = 4
        for seller in sellers :
            obj={}
            obj['seller'] = seller.name
            obj['total_price'] = 0
            p_qs = PurchaseDetail.objects.filter(orderdate__year= str(2018) ,  orderdate__month= str(01) , seller = seller)
            
            for item in p_qs:
                obj['total_price'] += int(item.total_price)

            result_data.append(obj);
             
        return result_data


        
class PurchaseDetail(TimeStampedModel):
    id = models.AutoField(primary_key=True)
    material =  models.ForeignKey('mst.Material')
    seller = models.ForeignKey('mst.Seller', blank=True, default = 1)
    count = models.CharField(max_length=200, default = 1)
    now_unit_price = models.CharField(max_length=200)
    total_price = models.IntegerField(default = 0)
    comment = models.CharField(max_length=200, blank=True)
    orderdate = models.DateField(default=timezone.now, verbose_name ="주문일자")

    class Meta:
        verbose_name = '*매입한 품목*'
        verbose_name_plural = '매입기록들'
        db_table = 'purchasedetail' 
    
    def get_absolute_url(self):
        return u'/tiamo/purchase/%d/' % self.id 

    def __str__(self):
        return "일자별 매입한 품목"

    objects = PurchaseDetailManager()



class OrdersLogManager(models.Manager):
     
    def insert_orders_log(self, _client , _menuname , _comment, _date):
        client = _client
        if (isNumber(client) == False) :
            client = getClientByPosNum(_client)
        else :
            client = getClientById(_client)

        OrdersLog(client = client, order_txts = _menuname, comment = _comment, orderdate = _date).save()

    def delete_orders_log(self, _client, _date):
        OrdersLog.objects.filter(client = _client, orderdate = _date).delete()

class OrdersLog(TimeStampedModel):
    id = models.AutoField(primary_key=True)
    client = models.ForeignKey('mst.Client', blank=True, verbose_name ="주문처")
    order_txts = models.CharField(max_length=100, blank = False, verbose_name = "판매기록") 
    orderdate = models.DateField(default=timezone.now, verbose_name ="주문일자")
    comment   = models.CharField(max_length=100, blank = True, verbose_name = "특이사항") 

    class Meta:
        verbose_name = '*막장부 입력기록*'
        verbose_name_plural = '막장부'
        db_table = 'orders_log'

    def __str__(self):
        return "일자별 판매기록(막장부)"


    objects = OrdersLogManager()



class OrdersManager(models.Manager):
     
    def makeOrderDataSet(self, _client , _menuname , _comment, _date):
        client = getClientByPosNum( _client)
        product_list = getProductset( _menuname) #output [  ['투원냉', '3'], ['투매실', '2']  ]
        resultData = {'client' : client , 'product_list' : product_list, 'date' : _date}
        return resultData


    # _dataset = { 'client' : client ,'menuname': products
    #            , 'product_list' : product_list, 'date' : target_date
    #            , 'total_price' : total_price, 'coupon_total' : coupon_total}
    def upsertOrderData(self, _dataset):
        for p in _dataset.get('product_list'):
            defaults = { 'count' : p[1]}
            received = False
            if p[2] == 'coupon':
                is_coupon = True
            else:
                is_coupon = False

            try:
                obj = Orders.objects.get(
                    client = _dataset.get('client'), product = p[0], orderdate = _dataset.get('date'), is_coupon=is_coupon, received = received) 

                for key, value in defaults.items():
                    #조회된 obj 에 count 값 누적 
                    setattr(obj, key, int(value) + int(obj.count))
                    
                    obj.save()
            except Orders.DoesNotExist:
                new_obj = Orders.objects.create(
                    client = _dataset.get('client'), product = p[0], count = p[1], orderdate = _dataset.get('date'), is_coupon=is_coupon, received = received)
            except Exception, e:
                raise e
            
            logger.info("Order data updated %s(%d) - %s %d (coupon : %s)" % (_dataset.get('client').name,_dataset.get('client').id , p[0].name, int(p[1]), is_coupon ) );

        # Sales 테이블에 값을 업데이트 한다.
        Sales.objects.propagate_to_daily_order(
                            _dataset.get('date'), _dataset.get('client'))

        # Payment 테이블에 값을 업데이트 한다.
        Payment.objects.propagate_to_payment(_dataset.get('client'))


    def validateMenuNames(self, _menuname):
        product_list = getProductset( _menuname)
        return product_list

    def update_datas(self, client_id , target_date, products_txt):
        # get client
        client = Client.objects.get(id = client_id)

        product_list = getProductset( products_txt) #output [  ['투원냉', '3'], ['투매실', '2']  ]

        total_price = get_total(product_list)

        #TODO applied_coupon 이 없네?!
        order_dataset = {'client' : client, 'product_list' : product_list, 'date' : target_date}

        #TODO: transaction start
            # delete data ranged in orderdate
        
        Orders.objects.filter(orderdate = target_date,client = client, received=False).delete()
            # save data 
 
        Orders.objects.upsertOrderData(order_dataset)
        #TODO: transaction end
        return total_price

    # 기간안에 속하는 모든 거래처의 거래기록을 조회한다.
    def get_OrderData_all(self, start_date, end_date):
        
        total_order_recodes = None
        _clients_list = []
        if end_date is None:
            end_date = start_date

        logger.debug("%s %s" % (start_date, end_date))
        total_order_recodes = Orders.objects.filter(orderdate__range = (start_date, end_date) ).order_by('client__posnumber','client__segment')
        total_order_recodes.prefetch_related('client','product','comment','id','received')

        for item in total_order_recodes:
            if item.client not in _clients_list:
                _clients_list.append(item.client)
        return self.getOrderDatas( start_date, end_date, _clients_list = _clients_list, _datasets= total_order_recodes)



    def get_order_history_by_client_id(self, client, date_until ):
        logger.debug("Orders.get_order_history_by_client_id(client = %s , date_until = %s)" % (client.id, date_until))

        total_order_recodes = None
        result_data = []
        orderdatas = []
        total_order_recodes = Orders.objects.filter(client = client, received = False, orderdate__lte = date_until)

        for order in total_order_recodes:
            if order.orderdate not in orderdatas:
                orderdatas.append(order.orderdate)

                obj = {}
                obj['orderdate'] = order.orderdate.strftime('%Y%m%d')
                obj['products'] = ''
                obj['total_sales'] = 0

                coupon_txt = ''
                if not order.is_coupon :
                    # 합계금액 누적 
                    obj['total_sales'] += int(order.product.selling_price) * order.count
                else:
                    coupon_txt = "(C)"

                if order.count == 1:
                    order.count = ''
                # 판매상품 목록 작성
                obj['products'] += order.product.name + " " + str(order.count) + coupon_txt
                result_data.append(obj)
            else:
                for i in xrange(0,len(result_data)):
                    coupon_txt = ''
                    if result_data[i].get('orderdate') == order.orderdate.strftime('%Y%m%d'):
                        if not order.is_coupon :
                            # 합계금액 누적 
                            result_data[i]['total_sales'] += int(order.product.selling_price) * order.count
                        else:
                            coupon_txt = "(C)"

                        if order.count == 1:
                            order.count = ''
                        # 판매상품 목록 작성
                        result_data[i]['products'] += ", "+order.product.name + " " + str(order.count) + coupon_txt

        return  result_data

    def get_product_text_today(self, client, orderdate):
        product_txt  = ''
        coupon_txt = ''
        order_qs = Orders.objects.filter(client=client, received = False, orderdate = orderdate)
        for item in order_qs :
            if item.count == 1 :
                item.count = ''
            if item.is_coupon :
                coupon_txt = "(C)"
            product_txt +=  item.product.name + " " + str(item.count) + coupon_txt +", "



        return product_txt[:-2] 

    def getOrderDatas(self, start_date, end_date , _clients_list , _datasets):
        logger.debug("start_date = %s, end_date = %s " % (start_date, end_date) )

        result_data=[]
        total_order_recodes = _datasets

        if len(_datasets) == 0 :
            logger.debug("Orders.getOrderDatas() returned. order data is none")
            return None

        # 오늘의 client 목록을 기준으로 표시할 데이터를 만든다.
        for u_client in _clients_list:
            obj = {}
            obj['orderdate'] = start_date.strftime('%Y%m%d')
            if len(_clients_list) >= 1:
                obj['client'] = u_client

            for data in total_order_recodes:
                if u_client.id ==  data.client_id:
                    obj['received'] = data.received
                    if obj.has_key('products') : # 맨 처음이 아니면

data/tiamo/forms.py
# -*- coding: utf8 -*-
from django import forms
from tiamo.models import *
import datetime
class PurchaseDetailForm(forms.Form):
    material = forms.ModelChoiceField(empty_label="품명",queryset=Material.objects.all())
    seller = forms.ModelChoiceField(initial="취급처",queryset=Seller.objects.all())
    count = forms.IntegerField(initial='1',help_text="수량")
    now_unit_price = forms.IntegerField(help_text="단가")
    total_price =  forms.IntegerField(help_text="합계")
    comment = forms.CharField()
    orderdate = forms.DateField(initial=datetime.date.today) #,"%y-%m-%d"

    def __init__(self, *args,**kwargs):
        seller = kwargs.pop('seller', None)
        super(PurchaseDetailForm, self).__init__(*args, **kwargs)

        if seller:
            self.fields['material'].queryset = Material.objects.filter(seller_id=seller)
            
            self.fields['seller'].queryset = Seller.objects.filter(id = seller)
            self.fields['seller'].initial=seller

# class OrdersForm(forms.ModelForm):
    # class Meta:
    #     model = Orders
    #     fields = ['client','menuname','order_count','comment']

    #     # Overriding default fields
    #     widgets = {
    #         'client' : forms.TextInput( attrs={'class': 'form-control',}),
    #         'menuname' : forms.TextInput( attrs={'class': 'form-control',}),
    #     }

    #     customize fields
    #     help_texts = {
    #         'menuname': _('투원냉,설반,원대2...')
    #     }
    #     error_messages = {
    #         'menuname' :{
    #             'invaild_string' : _("투원냉,설반,원대2...")
    #         }
    #     }

        

data/tiamo/templates/payment/payment_time_list.html
 {% extends "base_generic.html" %}

 {% block content %}
<style type="text/css">
.warning-placeholder::-webkit-input-placeholder {
    color: #ff0000
}

.btn-default {
    width: 120px;
    box-shadow: 0 8px 4px 0 rgba(0,0,0,0.2), 0 0px 1px 0 rgba(0,0,0,0.19);
    margin: 2px
}

#dialog-message { }
#deferd_list {border-top-width: 2; margin-bottom: 10px;}
#completed_list {border-top-width: 2; margin-bottom: 10px;}
#tabs-1-list {margin-bottom: 10px; width: 70%;}
#tabs-2-list {margin-bottom: 10px; width: 70%;}
#tabs-3-list {margin-bottom: 10px; width: 70%;}
table tbody tr th{ width: 130px;}

</style>

<script type="text/javascript"></script>

<h1> {{date|date:'Y m. d'}} 정산대상</h1> 

<div id="dialog-message" title="거래내역">
  <div id="dialog-body"></div>
</div>

<div id="tabs">
<ul>
  <li><a href="#tabs-1">4F </span></a></li>
  <li><a href="#tabs-2">3F</a></li>
  <li><a href="#tabs-3">그 외</a></li>
</ul>

<div id="tabs-1" >
  <div class="row">

  <div id="tabs-1-list" class="col-xs-6">

    {% if 4flist %} 
    A  
      {% for data in 4flist %}
      {% if data.client.segment == 'A' %}
          {% include 'payment/payment_time_list_detail.html' %}
      {% endif %}
      {% endfor%}

      B
      {% for data in 4flist %}
      {% if data.client.segment == 'B' %}
          {% include 'payment/payment_time_list_detail.html' %}
      {% endif %}
      {% endfor%}
      C
      {% for data in 4flist %}
      {% if data.client.segment == 'C' %}
          {% include 'payment/payment_time_list_detail.html' %}
      {% endif %}
      {% endfor%}
      N
      {% for data in 4flist %}
      {% if data.client.segment == 'N' %}
          {% include 'payment/payment_time_list_detail.html' %}
      {% endif %}
      {% endfor%}
  </div>  <!-- end of accordion -->  <!-- segment == A-D -->

    {% else %}
      <div id = "noData" class="col-xs-6">
        표시할 데이터가 없네요.
      </div>
    {% endif %}

    <div class="col-xs-6">
      <!-- 공백  -->
    </div> 
    
</div> <!-- end of row -->
</div> <!-- end of tabs-1 -->

{% include 'payment/payment_time_list_3f.html' %}
{% include 'payment/payment_time_list_2f_5f_etc.html' %}







 <script type="text/javascript">
$(document).ready(function() {
  $( "#tabs-1-list" ).accordion({
    collapsible: true
  });
  $( "#tabs-2-list" ).accordion({
    collapsible: true
  });
  $( "#tabs-3-list" ).accordion({
    collapsible: true
  });
  $( "#deferd_list" ).accordion({
    collapsible: true
  });
  $( "#completed_list" ).accordion({
    collapsible: true
  });

  $( "#tabs" ).tabs();
  
  $('#date').datepicker({dateFormat:'yy-mm-dd'});
      

});


function send_received_date_to_server(client_id, until_date){
  $.ajax({
    dataType: 'json',
    url: '/tiamo/payment/received/',
    type:'POST',
    data: { 
        'client_id': client_id,
        'until_date': until_date,
        'csrfmiddlewaretoken': '{{ csrf_token }}'}, 
    success: function (data){
        if (data.msg == 'success'){
          //data 갱신
          var item = "<h3> "+$("#c_name-"+client_id).val()+"</h3>"
          $('#completed_list ul' ).append(item);
          //초기화
          $('#detail-'+client_id).remove();
          $('#client-'+client_id).remove();
        } else {
          console.log(data.msg);
          $('#msg').val(data.msg);
        }
    } // end of success
  });  //end of ajax
};

function send_received_money_to_server(client_id, received_money){
  alert(received_money);
  // received_date는 돈 받은 날짜임. 테스트용. 임의의 날짜로 수금처리하고자 할 때 사용함.
  $.ajax({
    dataType: 'json',
    url: '/tiamo/payment/received/',
    type:'POST',
    data: { 
        'client_id': client_id,
        'payment_amount': received_money,
        'csrfmiddlewaretoken': '{{ csrf_token }}'}, 
    success: function (data){
        console.log(data);
        if (data.msg == 'success'){
          //data 갱신
          var item = "<h3> "+$("#c_name-"+client_id).val()+"</h3>"
          $('#completed_list ul' ).append(item);
          //초기화
          $('#detail-'+client_id).remove();
          $('#client-'+client_id).remove();
        } else { console.log(data);}
    } // end of success
  });  //end of ajax
};
function payment_received(client_id){
  // received_date는 돈 받은 날짜임. 테스트용. 임의의 날짜로 수금처리하고자 할 때 사용함.
  $.ajax({
    dataType: 'json',
    url: '/tiamo/payment/received/',
    type:'POST',
    data: { 
        'client_id': client_id,
        'csrfmiddlewaretoken': '{{ csrf_token }}'}, 
    success: function (data){
        if (data.msg == 'success'){
          //data 갱신 
          var item = "<h3> "+$("#c_name-"+client_id).val()+"</h3>"
          $('#completed_list ul' ).append(item);
          // 초기화
          $('#detail-'+client_id).remove();
          $('#client-'+client_id).remove();
        } else { console.log(data);}
    } // end of success
  });  //end of ajax
};

 // base_generic.html > input_money_amount ()

  //금액입력 용 태그 보이기
  function show_received_amount_box (client_id) {
    $('#dialog-body').html(input_money_amount(client_id));
    $('#dialog-message').dialog({
      modal: true,
      title: "부분결제 금액지정",
      buttons: {
        Cancel: function() {
          $('#error_span').hide();
          $( this ).dialog( "close" );
        },
        Confirm: function(){
          var received_money = $('#received_'+client_id+'_money').val();
          if (received_money > 500) {
            send_received_money_to_server(client_id, received_money);
            $( this ).dialog( "close" );
          }
          else{
            $('#received_money').addClass('warning-placeholder');
            $('#error_span').show();
            console.log("받은 금액 오류!");
          }
        } 
      }
    }); 
  };

  //날짜입력 용 다이얼로그 보이기
  function show_received_date_box (client_id) {
    $('#dialog-body').html(input_date_body(client_id));
    $('.datepicker').datepicker({dateFormat:'yy-mm-dd'});
    $('#dialog-message').dialog({
      modal: true,
      title:"수금한 날짜지정",
      buttons: {
        Cancel: function() {
          $( this ).dialog( "close" );
        },
        Confirm: function(){
          var until_date = $('#date_'+client_id+'_datepicker').val();
          if (until_date){
            
            send_received_date_to_server(client_id, until_date);
            $( this ).dialog( "close" );
          }
          else{
            console.log("날짜 입력 오류 ");
          }
        } 
      }
    }); 
  };
 
  function input_date_body(client_id){
    var result_data = ''
    result_data += "<div id = \"input_date\" "
    result_data += "<label for=\"date\">DATE :</label> <input id=\"date_"+client_id+"_datepicker\"  class=\"datepicker\" type=\"text\" name=\"date\"/>"
    result_data += "<a href='javascript:void(0);' onclick=\"setDateToday()\"><b>오늘</b></a>"
    result_data += "<p id=\"msg\"></p></div>"
                          
    return result_data
  };


// base_generic.html > history_data (data)
// base_generic.html > show_order_history(client_id)
 


  function defer_data(client_id) {
    var result = ""
    var title = "연기 날짜지정"
    result += "<label for=\"defer_date\">연기 날짜:</label>"
    result += "<input type=\"date\"  name=\"somedate\" id=\"date_"+client_id+"_defer\"/>"
    return result

// <input type="button" onclick="" value="전송">

  };
  
  //다음 지정일 용 달력 보이기
  function show_defer_box (client_id) {
    $('#dialog-body').html(defer_data(client_id));
    $('#dialog-message').dialog({
      modal: true,
      buttons: {
        Cancel: function() {
          $( this ).dialog( "close" );
        },
        Confirm: function(){
          defer_payment(client_id);
          $( this ).dialog( "close" );
        }
      }
    });
  };

  function defer_payment(client_id){
    var id = "client-"+client_id;
    var defer_date = $('#date_'+client_id+'_defer').val();
    $.ajax({
      dataType: 'json',
      url: '/tiamo/payment/defer/',
      type:'POST',
      data: { 
          'client_id': client_id,
          'defer_date': defer_date,
          'csrfmiddlewaretoken': '{{ csrf_token }}'}, 
      success: function (data){
          console.log(data);
          if (data.msg == 'success'){
            var item = "<h3> "+$("#c_name-"+client_id).val()+"</h3>"
            $('#deferd_list ul' ).append(item);
            $('#detail-'+client_id).remove();
            $('#client-'+client_id).remove();
          }
      } // end of success
    });  //end of ajax 
  };
 
  

  

  // //autocomplete
  // $('#id_client').autocomplete({
  //     source: l_client_posnum
  // });
  
  
  // TODO: (중요) ********************************************
  // 나중에 function 들은 모두 /body 앞으로 모두 이동한다. 
  // full_payment()함수도 defer_payment()를 참고하여 이동할 수  있다.
</script>
{% endblock %}